#include "infinite_grid_renderer.hh"

#include <triengine/utility/debug_utils.hh>
#include <triengine/shaders/infinite_grid_shaders.h>

namespace triengine::renderer
{
    infinite_grid_renderer::infinite_grid_renderer()
    { }

    void infinite_grid_renderer::create_impl(core::gl_context& glctx, const core::shader_preprocessor& shader_prep)
    {
        TRIENGINE_ASSERT(!this->is_created());
        this->set_creation_flag(true);

        ::glfwMakeContextCurrent(glctx.get_glfw_window());

        //
        // Context Settings
        //

        // Create shader program
        _shader
            .attach_vertex_shader({ shaders::glslShaderVersion, shader_prep.process_from_memory(shaders::kInfiniteGridVertexShader).c_str() })
            .attach_fragment_shader({ shaders::glslShaderVersion, shader_prep.process_from_memory(shaders::kInfiniteGridFragmentShader).c_str() })
            .link();

        // Create empty VAO (for avoid INVALID_OPERATION draw-call error)
        GLCall(::glGenVertexArrays(1, &_vao));
    }

    void infinite_grid_renderer::destroy_impl()
    {
        if (this->is_created())
        {
            this->set_creation_flag(false);

            GLCall(::glDeleteVertexArrays(1, &_vao));

            _shader.destroy();
        }
    }

    void infinite_grid_renderer::render_impl(const render_context& render_ctx)
    {
        if (render_ctx.curr_render_pass != render_pass_type::wboit_transparent_rendering) {
            return;
        }

        // Enable depth testing
        //GLCall(::glEnable(GL_DEPTH_TEST));

        // Save previous state
        //GLint prev_blend_state{};
        //GLCall(::glGetIntegerv(GL_BLEND, &prev_blend_state));
        //GLint prev_blend_src_state{};
        //GLCall(::glGetIntegerv(GL_BLEND_SRC, &prev_blend_src_state));

        // Enable blending
        //GLCall(::glEnable(GL_BLEND));
        //GLCall(::glBlendFunc(GL_SRC_ALPHA, GL_ONE_MINUS_SRC_ALPHA));

        _shader.use();
        _shader.set_uniform_mat4("u_view", render_ctx.view);
        _shader.set_uniform_mat4("u_proj", render_ctx.projection);

        _shader.set_uniform_vec3("u_eyePos", render_ctx.camera->get_position());
        _shader.set_uniform_vec3("u_gridColor", _options.grid_color);
        _shader.set_uniform_float("u_gridCellSize", _options.grid_cell_size);

        // Bind empty VAO for avoid INVALID_OPERATION draw-call error
        // Ref: https://registry.khronos.org/OpenGL/specs/gl/glspec46.core.pdf (10.3. VERTEX ARRAYS)
        //      "An INVALID_OPERATION error is generated by any commands which modify, draw from, or query vertex array state when no vertex array is bound."
        GLCall(::glBindVertexArray(_vao));

        // Render grid
        GLCall(::glDrawArrays(GL_TRIANGLES, 0, 6));

        // https://registry.khronos.org/OpenGL-Refpages/gl4/html/glBindVertexArray.xhtml
        // https://www.reddit.com/r/opengl/comments/f3sclv/comment/fhkou86/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button
        // `glBindVertexArray(0)` will unbind any bound VAO. 
        // I mean, as long as you always bind another VAO before you draw another object, you really don't have to do this.
        //GLCall(::glBindVertexArray(0));

        // Restore previous state
        //if (prev_blend_state) {
        //    GLCall(::glEnable(GL_BLEND));
        //} else {
        //    GLCall(::glDisable(GL_BLEND));
        //}
        //GLCall(::glBlendFunc(GL_SRC_ALPHA, prev_blend_src_state));
    }

} // namespace