<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <ImportGroup Label="PropertySheets" />
  <PropertyGroup Label="UserMacros">
    <CommonIncludesDir>$(SolutionDir)examples\common-includes</CommonIncludesDir>
  </PropertyGroup>
  <PropertyGroup>
    <OutDir>$(SolutionDir)bin\$(Platform)-$(Configuration)\$(ProjectName)\</OutDir>
    <IntDir>$(SolutionDir)build\$(ShortProjectName)\$(Platform)-$(Configuration)\</IntDir>
    <IncludePath>$(SolutionDir)triengine-installed\$(Platform)-$(Configuration)\include;$(SolutionDir)triengine-installed\$(Platform)-$(Configuration)\include\triengine\extern\imgui;$(SolutionDir)triengine-installed\$(Platform)-$(Configuration)\include\triengine\extern\implot;$(CommonIncludesDir)\include;$(IncludePath)</IncludePath>
    <LibraryPath>$(SolutionDir)triengine-installed\$(Platform)-$(Configuration)\lib;$(LibraryPath)</LibraryPath>
  </PropertyGroup>
  <ItemDefinitionGroup>
    <ClCompile>
      <WarningLevel>Level4</WarningLevel>
      <LanguageStandard>stdcpp17</LanguageStandard>
      <PreprocessorDefinitions>NOMINMAX;WIN32_LEAN_AND_MEAN;%(PreprocessorDefinitions)</PreprocessorDefinitions>
      <AdditionalOptions>/utf-8 %(AdditionalOptions)</AdditionalOptions>
    </ClCompile>
    <Link>
      <AdditionalDependencies>triengine.lib;%(AdditionalDependencies)</AdditionalDependencies>
    </Link>
  </ItemDefinitionGroup>
  <ItemGroup>
    <BuildMacro Include="CommonIncludesDir">
      <Value>$(CommonIncludesDir)</Value>
    </BuildMacro>
  </ItemGroup>
</Project>