# scripts/binpack.py

import sys
import os
import io
import zipfile
import math

def format_size(size_bytes):
    """Converts a size in bytes to a human-readable format (B, KB, MB, GB)."""
    if size_bytes == 0:
        return "0 B"
    size_names = ("B", "KB", "MB", "GB", "TB")
    i = int(math.floor(math.log(size_bytes, 1024)))
    p = math.pow(1024, i)
    s = round(size_bytes / p, 2)
    return f"{s} {size_names[i]}"

def main():
    """
    Packs specified files into an in-memory zip archive
    and converts the archive into a C++ header file.
    """

    if len(sys.argv) < 5:
        print(f"Usage: python3 {os.path.basename(sys.argv[0])} <output_header> <variable_name> <base_dir> <file1> [<file2> ...]")
        sys.exit(1)

    output_path = sys.argv[1]
    variable_name = sys.argv[2]
    base_dir = sys.argv[3]
    input_files = sys.argv[4:]  # The rest of the arguments are input files
    bytes_per_line = 12
    
    print(f"{'-'*31} binpack.py start {'-'*31}")
    print(f"Output header: {output_path}")
    print(f"C++ variable:  {variable_name}")
    print(f"Found {len(input_files)} file(s) to pack:")
    for file_path in input_files:
        print(f"  - {file_path}")

    # Create the Zip archive in-memory
    zip_buffer = io.BytesIO()
    total_original_size = 0

    # Use zipfile.ZIP_DEFLATED for compression
    with zipfile.ZipFile(zip_buffer, 'w', zipfile.ZIP_DEFLATED) as zf:
        for file_path in input_files:
            try:
                # Calculate the path as it should appear inside the archive
                arcname = os.path.relpath(file_path, base_dir)
                
                # Add file to the archive
                zf.write(file_path, arcname)
                total_original_size += os.path.getsize(file_path)

            except FileNotFoundError:
                print(f"Warning: Input file not found, skipping: '{file_path}'")
                continue
    
    # Get the final binary data of the zip archive from the memory buffer
    zip_binary_data = zip_buffer.getvalue()
    compressed_size = len(zip_binary_data)

    # Build the C++ header content
    output_lines = [
        f"// Auto-generated by 'binpack.py'",
        "// DO NOT EDIT BY HAND!",
        "#pragma once",
        "",
        f"static const unsigned char {variable_name}[] = {{",
    ]
    
    # Convert binary data to a C-style hex array
    for i in range(0, len(zip_binary_data), bytes_per_line):
        chunk = zip_binary_data[i:i + bytes_per_line]
        hex_line = ", ".join(f"0x{byte:02x}" for byte in chunk)
        output_lines.append(f"    {hex_line},")

    output_lines.append("};")
    output_lines.append("")

    # Also add a size variable for convenience
    output_lines.append(f"static const unsigned int {variable_name}_size = sizeof({variable_name});")
    output_lines.append("")

    # Write the content to the output header file
    try:
        with open(output_path, 'w', newline='\n') as f_out:
            f_out.write("\n".join(output_lines))
    except IOError as e:
        print(f"Error: Could not write to output file '{output_path}': {e}")
        sys.exit(1)

    print(
        f"Total original size: {format_size(total_original_size)}\n"
        f"Compressed size: {format_size(compressed_size)}\n"
        f"All done!\n"
        f"{'-' * 80}"
    )

if __name__ == "__main__":
    main()